- hosts: all
  tasks: 
   - name: update /etc/hosts file
     lineinfile: 
           line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
           dest: /etc/hosts
           insertafter: BOF
