- name: Deploying Webserver
  hosts: all
  gather_facts: false
  remote_user: ansible
  tasks:
   - name: example of single line format
     file: path=/tmp/xyz state=directory mode=0777 owner=root group=root 

   - name: example of multi line format
     file: path=/tmp/xyz 
           state=directory
	   mode=0777
	   owner=root
	   group=root
   
   - name: example of dictionary format
     file:
         path: /tmp/xyz 
	 state: directory
	 mode: 0777 
	 owner: root 
	 group: root 
