- name: exampole of playbook level
  hosts: all
  vars: 
    mypkg: httpd 
    web_root: /var/www/html 
    app: krnetwor-2.0.0.1.war
  tasks:
     - name: install the package
       yum: 
         name: "{{ mypkg }}"
         state: installed 

     - name: create document root
       file: 
          path: "{{ web_root }}"
          state: directory

     - name: copy "{{ app }}" into "{{ web_root}}"
       copy: 
           src: "/home/ansible/PLAYBOOK/Variables/{{ app }}"
           dest: "{{ web_root }}"

